### ISSUE TITLE
Cannot read properties of null (reading 'login')

### ISSUE THREAD

**Issue by ArthurNRL** [mikesprague/teams-incoming-webhook-action#143]
Getting an error while using deploy-card: true
```
      - name: Send message
        uses: mikesprague/teams-incoming-webhook-action@v1.10.3
        with:
          github-token: ${{ inputs.token }} # this will use the runner's token.
          webhook-url: ${{ inputs.webhook-url }}
          color: ${{ inputs.level }}
          title: ${{ inputs.message }}
          deploy-card: true
```
```
TypeError: Cannot read properties of null (reading 'login')
    at populateCard (file:///D:/a/_actions/mikesprague/teams-incoming-webhook-action/v1.10.3/webpack:/teams-incoming-webhook-action/src/lib/cards/deploy.ts:39:1)
Error: Cannot read properties of null (reading 'login')
    at file:///D:/a/_actions/mikesprague/teams-incoming-webhook-action/v1.10.3/webpack:/teams-incoming-webhook-action/src/index.ts:97:1
    at Generator.next (<anonymous>)
    at fulfilled (file:///D:/a/_actions/mikesprague/teams-incoming-webhook-action/v1.10.3/webpack:/teams-incoming-webhook-action/src/index.ts:28:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by mikesprague** [comment]
I'll need some more information if you want help with this, such as the complete workflow and the full logs from the failed Workflow run.

It looks like you're using the Action differently than documented since you are using inputs to populate it. 

If I had to guess, you are trying to use it in a reusable workflow and not passing the required info from the calling workflow but that's just a guess with the limited information supplied.

**Comment by ArthurNRL** [comment]
Yes sure here you go:

```
## notify/action.yml
name: Notify
description: |
  This action will send a notification to a teams channel.
  

inputs:
  message:
    description: 'If true, only checks if cache entry exists and skips download. Does not change save cache behavior.'
    required: true
    default: false
  level:
    description: 'If true, only checks if cache entry exists and skips download. Does not change save cache behavior.'
    required: false
    default: 'info'
  token:
    description: 'Github token'
    required: true
  webhook-url:
    description: 'Teams webhook uri'
    required: true

runs:
  using: "composite"
  steps:
      - name: Send message
        uses: mikesprague/teams-incoming-webhook-action@v1.10.3
        with:
          github-token: ${{ inputs.token }} # this will use the runner's token.
          webhook-url: ${{ inputs.webhook-url }}
          color: ${{ inputs.level }}
          title: ${{ inputs.message }}
          deploy-card: true
```
all reuses look like this:

```
      - name: Notify dedicated teams channel
        uses: ./.github/actions/notify
        with:
          message: 'Build started'
          level: 'info'
          token: ${{ secrets.GITHUB_TOKEN }}
          webhook-url: ${{ secrets.MSTEAMS_WEBHOOK }}
```
setting git config username and email fixed it, but I'm afraid not everybody in my org has those set

**Comment by mikesprague** [comment]
The deploy card uses expected information built dynamically from the commit that initiated the workflow. And setting one's identity in Git is considered standard (and recommended <https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup>).

NOTE: when I refer to setting Git identity, I mean on the machine that makes the commit (NOT in the GH Actions environment). 

That said, if you don't think folks will have Git configured correctly, the deploy card might not be the best choice. You can also use the default/simple card and pass markdown in for formatting. Here's an example I use in another project:

```yaml

      - name: ⛔ Failure Notification
        if: ${{ failure() }}
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.TEAMS_ALERT_WEBHOOK_URL }}
          title: Workflow Failure - ${{ env.DISPLAY_NAME }}
          message: |
            **The last ${{ env.DISPLAY_NAME }} workflow run failed**

            Run logs: [${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
          color: failure
```

I'm still trying to decide if I'd consider this a bug vs it just being a case of non-standard usage since the deploy is intended to have the commit author information.

One option is to fork this repo, make the changes that support your use case, and then use your own version in your workflows.

It's also worth noting that since you are using it via reusable workflow that it might not be seeing all the data it needs from the calling workflow. I have not used it in that way as it's less work to call the Action itself then it is to wrap it and call that wrapper.

**Comment by ArthurNRL** [comment]
> setting one's identity in Git is considered standard 
Yes, mine was set, although my set username/email wasn't a valid github account but a bitbucket one.
Reading through the code it seems like you're just using `author` to display it's username/handle, couldn't you get this data from the commit itself? Here's how the commits looks on github(bottom one is with the "incorrect" configs)
![image](https://user-images.githubusercontent.com/63674393/234579741-d1b36f5a-4738-4ed7-9aac-bf28c81a2b92.png)

**Comment by mikesprague** [comment]
I hear what you are saying about author but this is the first time this has come up.

If you look at the code, I actually ignore it if author is not provided. 

If it's provided, it is expected to relate to a GitHub user because it is a GitHub Action running inside a GitHub Workflow on GitHub.com. I am not pointing that all out to be sarcastic, I am actually unsure how a bitbucket username is showing up inside your GitHub commit reference.

I'd probably need to see the full workflow logs to be more helpful.

**Comment by ArthurNRL** [comment]
```
Run mikesprague/teams-incoming-webhook-action@v1.10.3
  with:
    github-token: ***
    webhook-url: ***
    color: info
    title: Build started
    deploy-card: true
    timezone: America/New_York
  env:
    color: '17a2b8'
TypeError: Cannot read properties of null (reading 'login')
    at populateCard (file:///D:/a/_actions/mikesprague/teams-incoming-webhook-action/v1.10.3/webpack:/teams-incoming-webhook-action/src/lib/cards/deploy.ts:39:1)
Error: Cannot read properties of null (reading 'login')
    at file:///D:/a/_actions/mikesprague/teams-incoming-webhook-action/v1.10.3/webpack:/teams-incoming-webhook-action/src/index.ts:97:1
    at Generator.next (<anonymous>)
    at fulfilled (file:///D:/a/_actions/mikesprague/teams-incoming-webhook-action/v1.10.3/webpack:/teams-incoming-webhook-action/src/index.ts:28:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This was the full error logs.
I also get what you're saying, and for me this is solved, and if you want to close it it's fine. I just would do something to handle this and avoid more issues being opened in the future

**Comment by mikesprague** [comment]
If this is an actual bug, I want to fix it. I am trying to determine if it is that vs non-standard usage at this point.

Author is retrieved from the commit data by making a REST API call to get it: https://github.com/mikesprague/teams-incoming-webhook-action/blob/53c58630757080e03d00c86b0569640ce9bf630c/src/index.ts#L69-L71.

And, then if `login` isn't available it's not output: https://github.com/mikesprague/teams-incoming-webhook-action/blob/53c58630757080e03d00c86b0569640ce9bf630c/src/lib/cards/deploy.ts#L64

There should not be a case where GitHub cannot determine the author. That's why I feel the issue may be that not all the expected data is making it to the Action via your composite workflow.

In your case, it seems `author` is not there at all. Again, there really shouldn't be a case where GitHub cannot determine the commit author. 

This really feels more like an issue with the composite workflow usage vs an actual "bug" per se.

That said, I can see that a check for existence of `author` might handle this. The change is simple enough on my side and something I can publish in a patch release later this morning.

**Comment by ArthurNRL** [comment]
Ok you want the debug logs. I've taken the action out of the composite action for testing, here are the results:

```
##.github/workflows/build.yml
      - name: Send message
        uses: mikesprague/teams-incoming-webhook-action@v1.10.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-url: ${{ secrets.MSTEAMS_WEBHOOK }}
          color: 'info'
          title: "Build Started"
          deploy-card: true
```
with "wrong credentials":
```
##[debug]Evaluating condition for step: 'Send message'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Send message
##[debug]Loading inputs
##[debug]Evaluating: secrets.GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: secrets.MSTEAMS_WEBHOOK
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'MSTEAMS_WEBHOOK'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run mikesprague/teams-incoming-webhook-action@v1.10.3
  
TypeError: Cannot read properties of null (reading 'login')
    at populateCard (file:///D:/a/_actions/mikesprague/teams-incoming-webhook-action/v1.10.3/webpack:/teams-incoming-webhook-action/src/lib/cards/deploy.ts:39:1)
Error: Cannot read properties of null (reading 'login')
    at file:///D:/a/_actions/mikesprague/teams-incoming-webhook-action/v1.10.3/webpack:/teams-incoming-webhook-action/src/index.ts:97:1
    at Generator.next (<anonymous>)
    at fulfilled (file:///D:/a/_actions/mikesprague/teams-incoming-webhook-action/v1.10.3/webpack:/teams-incoming-webhook-action/src/index.ts:28:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Send message
```
With the "right" credentials workflow runs fine
