### ISSUE TITLE
Message field not properly populating/sending data.

### ISSUE THREAD

**Issue by LaithDaman** [mikesprague/teams-incoming-webhook-action#250]
Hello,

### Issue
(1) Can someone point out what could cause the issue here? I wanted to send the hyperlink in the "message" field but it does not seems to work.  I even tried plain text like `message: 'hello world!` and no difference in the output.
I was forced to put the link in the title and it works.  However, it will be nice to know why data in `message` field is not working.

(2) Also, how can I send multi-line info in the message (if I was able to get it to work properly).

### Background.
I am using self-hosed runner on AWS EC2 Windows 10 instance.

### yml code
```
      - name: Success Team notification
        if: ${{ success() }}
        uses: mikesprague/teams-incoming-webhook-action@v1.13.4
        with:
          github-token: ${{ secrets.MY_REPO_PAT }}
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URI }}
          deploy-card: true
          title: 'Nightly Build  -  [Nightly Releases Link](${{fromJson(steps.json_shared_link_result.outputs.content).shared_link.url}})'
          message: '[Nightly Releases Link](${{fromJson(steps.json_shared_link_result.outputs.content).shared_link.url}})'
          timezone: America/Denver
          color: 'success'
```

### Output
![image](https://github.com/mikesprague/teams-incoming-webhook-action/assets/135075794/df190120-993c-4c65-91a9-c3e6d11f138b)

**Comment by mikesprague** [comment]
It looks like you're combining parameters from the 2 sending options. If you take a closer look at the README you'll see it states that `message` is only available when `deploy-card` is set to `false` (and that the `deploy-card`s content is built dynamically from commit/repo info to send workflow status messages).

If you set `deploy-card` to `false`, the `message` parameter will work. You will not have some of the additional information included in when `deploy-card` is true but that is intended behavior, and you will have full control over the message content.

An example of a multi-line `message` would be:

```yaml
message: |
            **The last workflow run failed**

            Run logs: [${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
```

Hope that helps!
