### ISSUE TITLE
Moving a PR from Draft to Full PR state does not trigger a new notification

### ISSUE THREAD

**Issue by Rhernandez513** [mikesprague/teams-incoming-webhook-action#284]
Hi we are using `teams-incoming-webhook-action` like so:

```yml
name: Teams - PR Notification
on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Send notification to Teams"
        uses: mikesprague/teams-incoming-webhook-action@v1
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: "New Pull Request: ${{ env.PR_TITLE }}"
          message: "A new **Pull Request** is available for review [here](${{ env.PR_URL }})."
```

It works great for new PRs, but I noticed when moving a PR from Draft state to Open state with the Ready for Review button in Github, there was no new notification, or update to the original notification post
